name: python-app-1-ci/cd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set short SHA
        id: vars
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dmartin1642712/python-app-1:${{ steps.vars.outputs.short_sha }}
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Modify values.yaml file
        run: |
          echo ${{ needs.ci.outputs.short_sha }}
          pip install yq
          yq -Yi '.image.tag = "${{ needs.ci.outputs.short_sha }}"' charts/python-app-1/values-dev.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update values.yaml with commit ${{ needs.ci.outputs.short_sha }}"

      - name: Install ArgoCD CLI
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Login to ArgoCD
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }}

      - name: Create python-app-1 in ArgoCD
        run: |
          repo="https://github.com/martindouglasj-org/python-app-1.git"
          argocd repo list | grep $repo || argocd repo add $repo
          
          argocd app get python-app-1 || argocd app create python-app-1 \
          --repo $repo \
          --path charts/python-app-1 \
          --dest-namespace dev \
          --dest-server https://kubernetes.default.svc \
          --values values-dev.yaml \
          --revision main \
          --sync-policy manual \
          --sync-option CreateNamespace=true

      - name: Sync ArgoCD python-app-1 App
        run: |
          argocd app sync python-app-1
          argocd app wait python-app-1 --timeout 180